Load rabl for {ResponseSet,Survey}#to_json.
Without this require, it's possible for the Rabl constant to be
undefined when #to_json is invoked.  The error can be replicated in
Surveyor's testbed:

    ~/src/surveyor/testbed $ rails c
    >> rs = ResponseSet.first
    # => #<ResponseSet ...>
    >> rs.to_json
    NameError: uninitialized constant Surveyor::Models::ResponseSetMethods::Rabl